In [2]:
import numpy as np

In [8]:
grid = [
    [0,1,3,0,2,0,0,0,6],
    [0,5,0,0,8,0,0,0,0],
    [0,0,0,0,0,0,3,0,4],
    [0,0,0,0,6,4,0,0,1],
    [0,7,9,0,0,0,0,5,0],
    [0,0,0,0,0,0,7,0,0],
    [0,0,6,0,4,9,0,1,5],
    [0,0,0,8,0,1,9,0,0],
    [0,0,1,0,0,0,4,0,0],
]

print(np.matrix(grid))

[[0 1 3 0 2 0 0 0 6]
 [0 5 0 0 8 0 0 0 0]
 [0 0 0 0 0 0 3 0 4]
 [0 0 0 0 6 4 0 0 1]
 [0 7 9 0 0 0 0 5 0]
 [0 0 0 0 0 0 7 0 0]
 [0 0 6 0 4 9 0 1 5]
 [0 0 0 8 0 1 9 0 0]
 [0 0 1 0 0 0 4 0 0]]


In [9]:
# check if the number is valid for the given position
def is_valid(grid, row, col, num):
    # check if the number is already in the row
    for i in range(9):
        if grid[row][i] == num:
            return False

    # check if the number is already in the column
    for i in range(9):
        if grid[i][col] == num:
            return False

    # check if the number is already in the 3x3 box
    for i in range(3):
        for j in range(3):
            if grid[(row // 3) * 3 + i][(col // 3) * 3 + j] == num:
                return False

    return True

In [10]:
# check for empty cells
def find_empty_cell(grid):
    for i in range(9):
        for j in range(9):
            if grid[i][j] == 0:
                return (i, j)

    return None

In [11]:
# solve the sudoku
def solve_sudoku(grid):

    # find next empty cell
    empty_cell = find_empty_cell(grid)

    if empty_cell is None:
        return True

    row, col = empty_cell

    # try all numbers from 1 to 9
    for num in range(1, 10):
        if is_valid(grid, row, col, num):
            grid[row][col] = num

            if solve_sudoku(grid):
                return True

            grid[row][col] = 0

    return False

# solve the sudoku
solve_sudoku(grid)

True

In [12]:
print(np.matrix(grid))

[[9 1 3 4 2 7 5 8 6]
 [2 5 4 6 8 3 1 7 9]
 [6 8 7 9 1 5 3 2 4]
 [5 3 8 7 6 4 2 9 1]
 [4 7 9 1 3 2 6 5 8]
 [1 6 2 5 9 8 7 4 3]
 [7 2 6 3 4 9 8 1 5]
 [3 4 5 8 7 1 9 6 2]
 [8 9 1 2 5 6 4 3 7]]
