In [1]:
import numpy as np

In [7]:
grid = [
    [2,4,0,3,0,7,1,0,0],
    [3,0,0,0,2,0,0,0,0],
    [0,0,0,0,5,0,0,7,0],
    [9,0,0,1,0,3,0,8,0],
    [0,5,0,0,0,0,0,0,9],
    [0,0,0,2,0,0,0,0,0],
    [0,0,6,0,0,0,4,0,0],
    [0,0,0,0,7,0,0,0,0],
    [5,0,0,9,0,8,0,1,0],
]

print(np.matrix(grid))

[[2 4 0 3 0 7 1 0 0]
 [3 0 0 0 2 0 0 0 0]
 [0 0 0 0 5 0 0 7 0]
 [9 0 0 1 0 3 0 8 0]
 [0 5 0 0 0 0 0 0 9]
 [0 0 0 2 0 0 0 0 0]
 [0 0 6 0 0 0 4 0 0]
 [0 0 0 0 7 0 0 0 0]
 [5 0 0 9 0 8 0 1 0]]


In [8]:
# check if the number is valid for the given position
def is_valid(grid, row, col, num):
    # check if the number is already in the row
    for i in range(9):
        if grid[row][i] == num:
            return False

    # check if the number is already in the column
    for i in range(9):
        if grid[i][col] == num:
            return False

    # check if the number is already in the 3x3 box
    for i in range(3):
        for j in range(3):
            if grid[(row // 3) * 3 + i][(col // 3) * 3 + j] == num:
                return False

    return True

In [9]:
# check for empty cells
def find_empty_cell(grid):
    for i in range(9):
        for j in range(9):
            if grid[i][j] == 0:
                return (i, j)

    return None

In [10]:
# solve the sudoku
def solve_sudoku(grid):

    # find next empty cell
    empty_cell = find_empty_cell(grid)

    if empty_cell is None:
        return True

    row, col = empty_cell

    # try all numbers from 1 to 9
    for num in range(1, 10):
        if is_valid(grid, row, col, num):
            grid[row][col] = num

            if solve_sudoku(grid):
                return True

            grid[row][col] = 0

    return False

# solve the sudoku
solve_sudoku(grid)

True

In [11]:
print(np.matrix(grid))

[[2 4 9 3 6 7 1 5 8]
 [3 7 5 8 2 1 9 6 4]
 [6 1 8 4 5 9 3 7 2]
 [9 6 2 1 4 3 5 8 7]
 [4 5 1 7 8 6 2 3 9]
 [8 3 7 2 9 5 6 4 1]
 [7 8 6 5 1 2 4 9 3]
 [1 9 3 6 7 4 8 2 5]
 [5 2 4 9 3 8 7 1 6]]
